[supervisord]
nodaemon=true
user=root
# 【修改】将主进程日志写入真实文件，并开启 50MB 自动截断清理（自带防撑爆机制）
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=2

[program:web]
directory=/app/deploy
command=frankenphp run
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=50MB
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=50MB
autorestart=true

[program:schedule]
directory=/app
command=php artisan schedule:work
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=50MB
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=50MB
autorestart=true

[program:queue]
directory=/app
command=php artisan horizon
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=50MB
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=50MB
autorestart=true

# =========================================================
# 【新增】开一个专门的进程，把文件内容同步吐给 Docker 的标准输出
# 这样不仅网页能读到 /var/log/supervisord.log，
# 在外部运行 docker logs 依然能完美看到所有输出！
# =========================================================
[program:docker-logs]
command=tail -f /var/log/supervisord.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true